---
- name: Install chrony
  yum:
    name: chrony
    state: present

- name: Modify chrony.conf
  template:
    src:  chrony.conf.j2
    dest: /etc/chrony.conf
    force: yes
  notify:
  - Start and enable chronyd.service

- name: Modify hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_host }}   {{ item }}"
    state: present
  with_items: "{{ groups.cluster }}"

- name: Change hostnames
  hostname:
    name: "{{ inventory_hostname }}"
