---
- name: Install chrony
  yum:
    name: chrony
    state: present

- name: Modify chrony.conf
  template:
    src:  chrony.conf.j2
    dest: /etc/chrony.conf
    force: yes
  notify:
  - Start and enable chronyd.service

- name: Change hostname
  hostname:
    name: "{{ inventory_hostname }}"

