---
- name: Modify keystone.conf file (1)
  lineinfile:
    path: /etc/keystone/keystone.conf
    insertafter: '#memcache_servers = localhost:11211'
    line: 'memcache_servers = {{ hostvars[item].ansible_host }}:11211'
  with_items: "{{ groups.control }}"

- name: Modify keystone.conf file (2)
  lineinfile:
    path: /etc/keystone/keystone.conf
    insertafter: '#connection = <None>'
    line: 'connection = mysql+pymysql://keystone:{{ keystone_db_pass }}@{{ hostvars[item].ansible_host }}/keystone'
  with_items: "{{ groups.control }}"

- name: Modify keystone.conf file (3)
  lineinfile:
    path: /etc/keystone/keystone.conf
    insertafter: '#provider = fernet'
    line: 'provider = fernet'

- name: Keystone db sync
  become: yes
  become_user: keystone
  changed_when: false
  shell: >
    keystone-manage db_sync
  args:
    executable: /bin/bash

- name: Create fernet and credential keys for keystone
  command: "{{ item }}"
  with_items:
   - keystone-manage fernet_setup --keystone-user {{ keystone_user }} --keystone-group {{ keystone_group }}
   - keystone-manage credential_setup --keystone-user {{ keystone_user }} --keystone-group {{ keystone_group }}

- name: Bootstrap keystone
  command: >
    keystone-manage bootstrap --bootstrap-password {{ admin_pass }} --bootstrap-admin-url http://{{ hostvars[item].ansible_host }}:5000/v3/ --bootstrap-internal-url http://{{ hostvars[item].ansible_host }}:5000/v3/ --bootstrap-public-url http://{{ hostvars[item].ansible_host }}:5000/v3/ --bootstrap-region-id RegionOne
  with_items: "{{ groups.control }}"

- name: Install libsemanage-python
  yum:
    name: libsemanage-python
    state: present

- name: Modify httpd.conf file
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    insertafter: '#ServerName www.example.com:80'
    line: 'ServerName controller'
   
- name: Change boolean settings of httpd_use_openstack
  seboolean:
    name: httpd_use_openstack
    state: yes
    persistent: yes

- name: Change boolean settings of httpd_can_network_connect 
  seboolean:
    name: httpd_can_network_connect 
    state: yes
    persistent: yes

- name: Change boolean settings of httpd_can_network_connect_db 
  seboolean:
    name: httpd_can_network_connect_db 
    state: yes
    persistent: yes

- name: Open ports firewalld
  firewalld:
    port: 5000/tcp
    permanent: yes
    state: enabled
  notify:
  - Restart firewalld

- name: Check if /etc/httpd/conf.d/wsgi-keystone.conf exists
  stat:
    path: /etc/httpd/conf.d/wsgi-keystone.conf
  register: stat_result

- name: Create symbolic link 
  command: >
    ln -s /usr/share/keystone/wsgi-keystone.conf /etc/httpd/conf.d
  when: stat_result.stat.exists == False
  notify:
  - Start and enable httpd

- name: Create keystonerc file 
  template:
    src:  keystonerc.j2
    dest: ~/keystonerc
    owner: root
    group: root
    mode: 0600
    force: yes

- name: Modify keystone.conf file (3)
  lineinfile:
    path: ~/.bash_profile
    insertafter: 'export PATH'
    line: 'source ~/keystonerc'

