---
- name: Install nova-compute and qemu
  yum:
    name:  ['openstack-nova-compute','qemu-kvm','libvirt','virt-install']
    state: present
    enablerepo: centos-openstack-rocky

- name: Start and enable libvirtd service
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: Check bck.nova.conf file exists
  stat:
    path: /etc/nova/bck.nova.conf
  register: bck_nova

- name: Backup nova.conf file
  copy:
    src: /etc/nova/nova.conf
    dest: /etc/nova/bck.nova.conf
    remote_src: yes
  when: bck_nova.stat.exists == false

- name: Delete nova.conf file
  file:
    path: /etc/nova/nova.conf
    state: absent
  when: bck_nova.stat.exists == false

- name: Create nova.conf file
  template:
    src:  nova.conf.j2
    dest: /etc/nova/nova.conf
    owner: root
    group: nova
    mode: 0640
    force: yes

- name: Install openstack-selinux
  yum:
    name: openstack-selinux
    state: present
    enablerepo: centos-openstack-rocky

- name: Start and enable openstack-nova-compute.service
  service:
    name: openstack-nova-compute.service
    state: started
    enabled: yes

- name: Open ports firewalld
  firewalld:
    port: 5900-5999/tcp
    permanent: yes
    state: enabled
  notify:
  - Restart firewalld
