- name: Add https to firewalld
  firewalld:
    service: https
    permanent: yes
    state: enabled

- name: Add http to firewalld
  firewalld:
    service: http
    permanent: yes
    state: enabled
