---
- name: Wait until computes nodes are ready
  shell: >
    source ~/admin-openrc && openstack compute service list
  register: result
  until: not result.stdout.find("None") != -1
  retries: 120
  delay: 3

- name: Discover computer host
  become: yes
  become_user: nova
  shell: >
    nova-manage cell_v2 discover_hosts
  args:
    executable: /bin/bash
