---
- name: Install centos-release-openstack-rocky and epel repos
  yum:
    name: ['centos-release-openstack-rocky','epel-release']
    state: present

- name: Enable Centos Openstack Rocky repo
  replace:
    path: /etc/yum.repos.d/CentOS-OpenStack-rocky.repo
    regexp: 'enabled=1'
    replace: 'enabled=0'

- name: Add MariaDB 10.4 repo
  template:
    src:  MariaDB.repo.j2
    dest: /etc/yum.repos.d/MariaDB.repo
    force: yes

- name: Install MariaDB
  yum:
    name: MariaDB-server
    state: present

- name: Modify my.cnf file
  template:
    src:  my.cnf.j2
    dest: /etc/my.cnf
    force: yes

- name: Start and enable Mariadb service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Install MySQL-python
  yum:
    name: MySQL-python
    state: present

- name: Create dir "{{ checks_dir }}"
  file:
    path:  "{{ checks_dir }}"
    state: directory
    group: root
    owner: root
    mode: 0755

- name: Check if root password was set
  stat: 
    path: "{{ checks_dir }}/{{ check_MariaDB }}"
  register: MariaDB_root

- name: Secure root password
  mysql_user:
    name: root
    password: "{{ mysql_pass }}"
    host: "{{ item }}"
    state: present
  when: MariaDB_root.stat.exists == False
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
 
- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
  when: MariaDB_root.stat.exists == False

- name: Removes the MySQL test database
  mysql_db: 
    db: test
    state: absent
  when: MariaDB_root.stat.exists == False

- name: Create file "{{ check_MariaDB }}"
  file:
    path: "{{ checks_dir }}/{{ check_MariaDB }}"
    state: touch
    group: root
    owner: root
    mode: 0755

- name: Add mysql service firewalld
  firewalld:
    service: mysql
    permanent: yes
    state: enabled
  notify:
  - Restart firewalld
