---
- name: Install Memcached
  yum:
    name: memcached
    state: present

- name: Start and enable Memcached service
  service:
    name: memcached
    state: started
    enabled: yes

- name: Open port firewalld
  firewalld:
    port: 11211/tcp
    permanent: yes
    state: enabled
  notify:
  - Restart firewalld

