---
- hosts: control
  become: true
  roles:
    - 01-chrony-controller

#- hosts: nodes
#  become: true
#  roles:
#    - 02-chrony-nodes

- hosts: control
  become: true
  roles:
    - 03-rocky-packages

- hosts: control
  become: true
  roles:
    - 04-mariadb

- hosts: control
  become: true
  roles:
    - 05-rabbitmq

- hosts: control
  become: true
  roles:
    - 06-memcached

- hosts: control
  become: true
  roles:
    - 07-etcd

- hosts: control
  become: true
  roles:
    - 08-keystone-install

- hosts: control
  become: true
  roles:
    - 09-keystone-config

- hosts: control
  become: true
  roles:
    - 10-glance-install

- hosts: control
  become: true
  roles:
    - 11-glance-config

